version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "springboot/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
  - package-ecosystem: "gradle"
    directory: "quarkus/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
  - package-ecosystem: "gradle"
    directory: "micronaut/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2