image: gitpod/workspace-yugabytedb

tasks:
  - name: 1a-import-deps
    env:
      JAVA_VERSION: 17.0.7-librca
    init: |
      echo y | sdk install java $JAVA_VERSION || true
      gp sync-done jvm-17
  - name: 2a-spring-boot
    env:
      SPRING_PROFILES_ACTIVE: test
    before:
      cd springboot
    init: | 
      gp sync-await jvm-17
      gradle assemble
    command: |
      gradle test
