image: gitpod/workspace-yugabytedb

tasks:
  - name: 1a-ybdb
    env:
      HOST_LB: "127.0.0.1"
      HOST_LB2: "127.0.0.2"
      HOST_LB3: "127.0.0.3"
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --advertise_address=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1a --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --advertise_address=$HOST_LB2 --join=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1b --fault_tolerance=zone
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --advertise_address=$HOST_LB3 --join=$HOST_LB --cloud_location=ybcloud.ap-south-1.ap-south-1c --fault_tolerance=zone
      yugabyted configure --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --fault_tolerance=zone
  - name: 1b-ysqlsh
    command: |
      gp ports await 5433
      ysqlsh
  - name: 2a-install-postgres
    init:
      sudo install-packages postgresql-12 postgresql-contrib-12
    command: |
      sudo su postgres -c "pg_ctlcluster 12 main start"
      sudo su postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'postgres';\""
  - name: 2b-psql
    command: |
      gp ports await 5432
      sudo su postgres -c "psql"
  - name: 3a-install-jvm
    init: |
      echo y | sdk install java 17.0.5-librca || true
      gp sync-done jvm-17
  - name: 3b-spring-boot
    env:
      SPRING_PROFILES_ACTIVE: ysql
    before:
      cd springboot
    init: |
      gp sync-await jvm-17
      gradle build -x test
    command: |
      gp ports await 5433 && gp ports await 5432
      gradle bootRun --args='--spring.profiles.active=psql'
  - name: 3c-quarkus
    env:
      QUARKUS_PROFILE: ysql
    before:
      cd quarkus
    init: |
      gp sync-await jvm-17
      gradle quarkusBuild -x test
    command: |
      gp ports await 5433 && gp ports await 5432
      gradle -Dquarkus.profile=psql quarkusDev
  - name: 3d-micronaut
    env:
      MICRONAUT_ENVIRONMENTS: ysql
    before:
      cd micronaut
    init: |
      gp sync-await jvm-17
      gradle build -x test
    command: |
      gp ports await 5433 && gp ports await 5432
      MICRONAUT_ENVIRONMENTS=psql gradle run

# exposed ports
ports:
  - port: 8080
    name: spring-boot
    onOpen: notify
  - port: 8085
    name: quarkus
    onOpen: notify
  - port: 8090
    name: micronaut
    onOpen: notify
  - port: 7000
    name: yb-master-web
    onOpen: ignore
  - port: 9000
    name: yb-tserver-web
    onOpen: ignore
  - port: 7100
    name: yb-master-rpc
    onOpen: ignore
  - port: 9100
    name: yb-tserver-rpc
    onOpen: ignore
  - port: 5433
    name: ysql
    onOpen: ignore
  - port: 13000
    name: ysql-api
    onOpen: ignore
  - port: 9042
    name: ycql
    onOpen: ignore
  - port: 12000
    name: ycql-api
    onOpen: ignore
