image: gitpod/workspace-postgresql

tasks:
  - name: 1a-postgres
    command: |
      gp await-port 5432
      psql
  - name: 1b-import-deps
    before: |
      echo y | sdk install java 17.0.5-librca || true
      gp sync-done jvm-17
  - name: 2a-spring-boot
    before: | 
      cd springboot
      gp sync-await jvm-17
      gradle build -x test
    command: |
      gp await-port 5432
      gradle bootRun
  - name: 2b-quarkus
    before: | 
      cd quarkus
      gp sync-await jvm-17
      gradle quarkusBuild -x test
    command: |
      gp await-port 5432
      gradle quarkusDev
  - name: 2c-micronaut
    before: | 
      cd micronaut
      gp sync-await jvm-17
      gradle build -x test
    command: |
      gp await-port 5432
      gradle run

# exposed ports
ports:
  - port: 8080
    name: spring-boot
    onOpen: notify
  - port: 8085
    name: quarkus
    onOpen: notify
  - port: 8090
    name: micronaut
    onOpen: notify
  - port: 5432
    name: psql
    onOpen: ignore
