image: gitpod/workspace-yugabytedb

tasks:
  - name: 1a-ybdb
    env:
      HOST_LB: "127.0.0.1"
    command: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb --advertise_address=$HOST_LB
  - name: 1b-ysqlsh
    command: |
      gp ports await 5433
      sleep 5
      ysqlsh
  - name: 2a-jvm-native
    env:
      JAVA_VERSION: 17.0.8-librca
      JAVA_NATIVE_VERSION: 21-graalce
    init: |
      echo y | sdk install java $JAVA_VERSION || true
      echo y | sdk install java $JAVA_NATIVE_VERSION || true
      gp sync-done jvm-17
  - name: 2b-spring-boot
    env:
      SPRING_PROFILES_ACTIVE: ysql
      JAVA_NATIVE_VERSION: 20.0.1-graalce
    before:
      cd springboot
    init: |
      gp sync-await jvm-17
      sdk use java $JAVA_NATIVE_VERSION
      gradle nativeCompile
    command: |
      ./build/native/nativeCompile/yb-boot-data
  - name: 2c-quarkus
    env:
      QUARKUS_PROFILE: ysql
      QUARKUS_PACKAGE_TYPE: native
      JAVA_NATIVE_VERSION: 20.0.1-graalce
    before:
      cd quarkus
    init: |
      gp sync-await jvm-17
      sdk use java $JAVA_NATIVE_VERSION
      gradle quarkusBuild -x test
#     gradle -Dquarkus.profile=ysql -Dquarkus.package.type=native quarkusBuild
    command: |
      gp ports await 5433
      ./build/yb-quarkus-data-1.0.0-runner
  - name: 2d-micronaut
    env:
      MICRONAUT_ENVIRONMENTS: ysql
      JAVA_NATIVE_VERSION: 20.0.1-graalce
    before:
      cd micronaut
    init: |
      gp sync-await jvm-17
      sdk use java $JAVA_NATIVE_VERSION
      gradle nativeCompile -x test
    command: |
      gp ports await 5433
      ./build/native/nativeCompile/yb-micronaut-data
