quarkus:
  application:
    name: yb-quarkus-data
  datasource:
    jdbc:
      initial-size: 5
      max-size: 20
      min-size: 5
      additional-jdbc-properties:
        currentSchema: qtodo
    db-kind: pgsql
  flyway:
    baseline-on-migrate: true
  http:
    port: 8085