quarkus:
  application:
    name: yb-quarkus-data
  datasource:
    jdbc:
      initial-size: 2
      max-size: 10
      min-size: 2
      new-connection-sql: "set search_path=qtodo,public;"
      additional-jdbc-properties:
        currentSchema: qtodo
    db-kind: pgsql
  flyway:
    default-schema: qtodo
    schemas: qtodo,public
    migrate-at-start: true

  http:
    port: 8085