spring:
  application:
    name: yb-boot-data
  flyway:
    default-schema: stodo
    schemas: stodo,public
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        default_schema: stodo
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: false
      keepalive-time: 120000
      connection-init-sql: "set search_path=stodo,public;"
server:
  port: 8080
