spring:
  flyway:
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: validate
#  datasource:
#    url: jdbc:tc:yugabyte:2.14.4.0-b26:///yugabyte
#    username: yugabyte
#    password: yugabyte
