micronaut:
  application:
    name: yb-micronaut-data
  router:
    static-resources:
      default:
        enabled: true
        paths: classpath:META-INF/resources
  server:
    port: 8090
datasources:
  default:
    auto-commit: false
    data-source-properties:
      currentSchema: mtodo
    minimum-idle: 5
    maximum-pool-size: 20
    keepalive-time: 120000
    connection-init-sql: "set search_path=mtodo,public;"
flyway:
  datasources:
    default:
      baseline-on-migrate: true
      default-schema: mtodo
      schemas: mtodo,public