
name: Quarkus CI with Gradle

on:
  push:
    branches: [ "main", "devx" ]
    paths:
      - quarkus/**
  pull_request:
    branches: [ "main", "devx" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: init-checkout
      uses: actions/checkout@v3
    - name: init-java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: init-gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - name: build-quarkus
      run: |
        cd quarkus
        gradle quarkusBuild -x test
